### ISSUE TITLE
For loops

### ISSUE THREAD

**Issue by Tomvandenberg11** [Sophievanderburg/get-inspired#11]
https://github.com/Sophievanderburg/get-inspired/blob/56d85b0c457b66fa87b2b436474907ac163d5016/modules/forms.js#L23-L31

Probeer .map of .filter te gebruiken ipv for loops. Dit vind ik een stuk overzichtelijker!
https://www.w3schools.com/jsref/jsref_map.asp

**Comment by Sophievanderburg** [comment]
sort of fixed it :)
