### ISSUE TITLE
Peerfeedback van Fabian Vis

### ISSUE THREAD

**Issue by fabian-vis** [Sophievanderburg/get-inspired#2]
Scan your buddy's repository
Is there a repo description at the top?
Er is nog geen beschrijving. Kan wat algemene uitleg over de app staan enz.

Is there a link to the live web app provided with GitHub Pages?
Die is er wel :)
Is the repo open to issues?
Ja

Does it include a gitignore
Jazeker

Is the concept described well in the readme?
Nog niet

Is the API described in the readme?
Nee

Code
Check the code for consistency, is code being written the same way in different places?
Ziet er consistent genoeg uit. Goede comments ook bij de CSS. maakt het een stuk overzichtelijker. Bij de JS zou ik wel nog een beetje naar de comments kijken.

Does the code follow naming conventions? Do variable and function names make sense to you?
Namen zijn over het algemeen duidelijk genoeg. Goed gebruik gemaakt van: ik heb geen idee hoe het heet maar: scrollKnop bijv.

Feel free to give feedback on HTML and CSS aswell!
Er staat nog een lege ul in de html, misschien was je daar nog mee bezig hoor maar goed

**Comment by Sophievanderburg** [comment]
Thanks voor de feedback! Ik heb het verwerkt.
