### ISSUE TITLE
antonio code review 

### ISSUE THREAD

**Issue by sietse333** [Sophievanderburg/get-inspired#3]
Scan your buddy's repository
Is there a repo description at the top?
There is no description yet

Is there a link to the live web app provided with GitHub Pages?
Yes

Is the repo open to issues?
Yes

Does it include a gitignore
Yes

Is the concept described well in the readme?
Nope there is no description yet

Is the API described in the readme?
Nope

Code
Check the code for consistency, is code being written the same way in different places?
Consistency is good. I see a few examples of english and dutch mixing but those are rare. So yeah good!

Does the code follow naming conventions? Do variable and function names make sense to you?
Names are clear

Feel free to give feedback on HTML and CSS aswell!
EMPTY UL SPOTTED. but looks clear

**Comment by Sophievanderburg** [comment]
Thanks for your feedback :)
