### ISSUE TITLE
Peer Feedback Tim de Roller

### ISSUE THREAD

**Issue by maggness** [Sophievanderburg/get-inspired#4]
**Scan your buddy's repository**
_Is there a repo description at the top?_
Yes with the pages link

_Is there a link to the live web app provided with GitHub Pages?_
Yes

_Is the repo open to issues?_
Yes

_Does it include a gitignore_
Yes

_Is the concept described well in the readme?_
No the readme is not yet edited

_Is the API described in the readme?_
No there is no description about the API

**Code**
_Check the code for consistency, is code being written the same way in different places?_
It looks consistent, only thing is the mix between dutch & english.

_Does the code follow naming conventions? Do variable and function names make sense to you?_
Its a mix of english & dutch, that should be changed to only dutch or preferably only english :)

_Feel free to give feedback on HTML and CSS aswell!_
i Like the design, scrolls feels good :) You can make it more accesible by adding a <nav> where you navigate the page

**Comment by Sophievanderburg** [comment]
thankss
