### ISSUE TITLE
Gebruik em ipv px

### ISSUE THREAD

**Issue by DaanKorver** [Sophievanderburg/get-inspired#6]
https://github.com/Sophievanderburg/get-inspired/blob/e00f86bfcef1a634159cc1de1c6c6274cc25e5a3/styles/style.css#L16

Het is handiger om em te gebruiken aangezien dit een responsive unit is in tegenstelling tot px wat een vaste waarde heeft

**Comment by Sophievanderburg** [comment]
Thanks voor de tip! Ik heb het aangepast
